In [1]:
import pandas as pd
df = pd.read_csv('layoffs.csv')

In [2]:
df

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised
0,Pear Therapeutics,Boston,Healthcare,170.0,0.92,2023-04-07,Post-IPO,United States,409.0
1,ZestMoney,Bengaluru,Finance,100.0,0.20,2023-04-07,Series C,India,120.0
2,Absolute Software,Vancouver,Security,40.0,0.05,2023-04-06,Post-IPO,Canada,NaN
3,Avocargo,Berlin,Transportation,16.0,1.00,2023-04-06,Seed,Germany,NaN
4,Dunzo,Bengaluru,Food,300.0,0.30,2023-04-05,Unknown,India,382.0
...,...,...,...,...,...,...,...,...,...
2468,HopSkipDrive,Los Angeles,Transportation,8.0,0.10,2020-03-13,Unknown,United States,45.0
2469,Panda Squad,SF Bay Area,Consumer,6.0,0.75,2020-03-13,Seed,United States,1.0
2470,Tamara Mellon,Los Angeles,Retail,20.0,0.40,2020-03-12,Series C,United States,90.0
2471,EasyPost,Salt Lake City,Logistics,75.0,NaN,2020-03-11,Series A,United States,12.0
2472,Blackbaud,Charleston,Other,500.0,0.14,NaN,Post-IPO,United States,NaN

In [4]:
df.isna().sum()

company                  0
location                 0
industry                 2
total_laid_off         777
percentage_laid_off    830
date                     1
stage                    6
country                  0
funds_raised           235
dtype: int64

In [5]:
df1=df.dropna()

In [6]:
df1

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised
0,Pear Therapeutics,Boston,Healthcare,170.0,0.92,2023-04-07,Post-IPO,United States,409.0
1,ZestMoney,Bengaluru,Finance,100.0,0.20,2023-04-07,Series C,India,120.0
4,Dunzo,Bengaluru,Food,300.0,0.30,2023-04-05,Unknown,India,382.0
5,Amplitude,SF Bay Area,Data,99.0,0.13,2023-04-05,Post-IPO,United States,311.0
7,Boost,New York City,Finance,15.0,0.20,2023-04-04,Series B,United States,37.0
...,...,...,...,...,...,...,...,...,...
2465,Inspirato,Denver,Travel,130.0,0.22,2020-03-16,Series C,United States,79.0
2466,Help.com,Austin,Support,16.0,1.00,2020-03-16,Seed,United States,6.0
2468,HopSkipDrive,Los Angeles,Transportation,8.0,0.10,2020-03-13,Unknown,United States,45.0
2469,Panda Squad,SF Bay Area,Consumer,6.0,0.75,2020-03-13,Seed,United States,1.0
2470,Tamara Mellon,Los Angeles,Retail,20.0,0.40,2020-03-12,Series C,United States,90.0

In [8]:
df1.isna().sum()

company                0
location               0
industry               0
total_laid_off         0
percentage_laid_off    0
date                   0
stage                  0
country                0
funds_raised           0
dtype: int64